config/routes.rb
Cs2048Homepage::Application.routes.draw do

  root :to => 'static_pages#home'

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/faq', to: 'static_pages#faq'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def about
	end

	def contact
	end

	def faq
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "CS2048"

    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li>Copyright 2013</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <!--<div class ="navbar-brand">-->
       <!-- <%= link_to image_tag('rails.png', mouseover: 'iphone_on.jpg'),
                   root_path, id: 'logo' %> -->

      <!--</div>-->
      <!--<nav>-->

        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Course Description", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "FAQ", faq_path %></li>

          </ul>

      <!--</nav>-->
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	 <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About')  %>
<div class="container">
  <p class="lead">About the course</p>
  <dl class="dl-horizontal">
    <dt>Instructor</dt>
    <dd>Tim Novikoff</dd>
    <dt>TA</dt>
    <dd>Seulgi Kim</dd>
    <dt>Location</dt>
    <dd>Thurston 203</dd>
    <dt>Office Hours</dt>
    <dd>Instructor : NONE<br/>
      TA : To Be Determined
    </dd>
  </dl>

  <br/>
  <br/>

  <p class="lead">Course Schedule</p>


  <table class="table table-striped">
    <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Materials covered</th>
    </tr>
    </thead>

    <tbody>
    <tr>
      <td>1</td>
      <td>Aug 31st</td>
      <td></td>
    </tr>

    <tr>
      <td>2</td>
      <td>Sep 7th</td>
      <td></td>
    </tr>

    <tr>
      <td>3</td>
      <td>Sep 21st</td>
      <td></td>
    </tr>

    <tr>
      <td>4</td>
      <td>Sep 28th</td>
      <td></td>
    </tr>
    </tbody>
  </table>

  <p class="text-error">
    There is NO CLASS on Sep 14th<br/>
    Final project is due on October 11th
  </p>


</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
Instructor : tpn9@cornell.edu <br/>
<br/>
TA : sk765@cornell.edu <br/>
<br/>
Do <strong>NOT</strong> email the instructor. Please email the TA instead unless the question is about a private matter.<br/>
The TA will forward questions to the instructor as necessary.<br/>
Also, check <%= link_to "FAQ", faq_path %> before sending any questions.
It is likely that other students have asked what you are about to ask.

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>

<div class="faq" id="faq1">
  <h1 class="question">1. What should I prepare for the first class?</h1>

  <p class="answer">
    <strong>Students are expected to show up on the first day of class with a computer running Mac OS 10.7 or later. The
      computer should have the latest version of XCode 4 already installed before class begins.</strong> Students can
    get XCode for free from the Mac App Store. It is an extremely large download, and it takes an extremely long time to
    install, and installation is occasionally problematic for some people, so students should be sure to complete both
    the download and installation by Friday August 30th in order to be absolutely sure that they have both downloaded
    and installed the latest version of XCode 4 prior to the beginning of the first class. Although there are rumors
    that the release of iOS 7 and XCode 5 are coming in September, the plan is to teach the entire course using iOS 6
    and XCode 4 exclusively.
  </p>
</div>

<div class="faq" id="faq2">
  <h1 class="question">2. What should I bring to each class?</h1>

  <p class="answer">
    Students should bring their laptop to each class. <strong>A Macbook is strongly recommended.</strong> Although it is
    possible to run XCode on non-mac computers, it is not recommended and students will not at all be helped with
    problems
    that arise from using non-mac laptops for development. Students do
    <strong>not need an iPhone or any iOS device to take the course.</strong> We'll be exclusively using the iPhone
    Simulator that comes with the latest version of XCode 4.
  </p>
</div>


<div class="faq" id="faq3">
  <h1 class="question">3. Is it okay if I miss the first class?</h1>

  <p class="answer">
    If you already have some iOS experience, it is fine to miss the first lecture. If you have no experience with any
    Integrated Development Environment (such as XCode or Eclipse), and you aren't willing to spend 10-15 hours before
    Lecture 2 figuring out XCode on your own, please either attend the first lecture or drop the course before the first
    lecture to make room for another student.
  </p>
</div>



<div class="faq" id="faq4">
  <h1 class="question">4. Is attendance required?</h1>

  <p class="answer">Attendance won't be taken, but all 4 assignments are mandatory. Assignments are extensions of what
    is covered during the lectures, so attendance is strong recommended.
  </p>
</div>

<div class="faq" id="faq5">
  <h1 class="question">5. Is there a pre-requisite?</h1>

  <p class="answer">
    <strong>CS2110 or basic understanding of OOP</strong> is required.<br/>
    The class assumes that students are familiar with OOP (Object Oriented Programming). The class will not go over
    basic OOP concepts, such as classes, instance variables, inheritance, etc. If you have passed CS 2110 or you are
    familiar with Java, you will be fine.
  </p>
</div>



<div class="faq" id="faq6">
  <h1 class="question">6. How is the course load?</h1>

  <p class="answer">
    There will be 4 assignments, including the final project. For your
    <strong>final project, you will develop an iPhone app of your choice using the skills that were covered in the
      course</strong>. The course is Pass/Fail.
  </p>
</div>


<div class="faq" id="faq7">
  <h1 class="question">7. Is it okay to email the instructor?</h1>

  <p class="answer">
    No. Please email the TA instead unless the question is about a private matter. The TA will forward questions to the
    instructor as necessary.
  </p>
</div>

<div class="faq" id="faq8">
<h1 class="question">8. Do I really need a Mac?</h1>
<p class="answer">
  <strong>It's very strongly recommended.</strong> You pretty much need XCode to develop iPhone apps, and you absolutely need it to follow this class, and XCode runs only on Mac OS X. There are ways to install Mac and XCode on Windows, but it isn't recommended for this class. Depending on how it's done it can run slowly, or fail entirely, and be difficult to trouble-shoot. In any case we won't be helping you with any issues that arise from this. You could try following these youtube videos at your own risk, but we suggest that you instead borrow a macbook from a friend, or if possible, the university.<br/>
  <a href="https://www.youtube.com/watch?v=Detp2hB-vhI">Installing Mac OS X on Windows</a><br/>
  <a href="http://www.youtube.com/watch?v=sb8BdYH4esQ">Installing XCode within Windows</a>
</p>
</div>
<div class="faq" id="faq9">
  <h1 class="question">9.Is this course awesome?</h1>

  <p class="answer">
    Objectively speaking, yes it is.
  </p>
</div>

app/views/static_pages/home.html.erb
<div class="hero-unit">
  <div class="container">
    <div class="title center">CS2048 - Intro to iPhone Development</div>


    <div class="well well-large announcement center">
      Please don't email the instructor. Email the TA ( sk765@cornell.edu ) instead.<br/>
    </div>

    <div class="center">
      <%= link_to "Course Description", about_path,
                  class: "btn btn-info btn-lg" %>
      &nbsp;&nbsp;&nbsp;
      <%= link_to "Contact", contact_path,
                  class: "btn btn-info btn-lg" %>
      &nbsp;&nbsp;&nbsp;
      <%= link_to "FAQs", faq_path,
                  class: "btn btn-info btn-lg" %>

    </div>
  </div>
</div>